// ═══════════════════════════════════════════════════════════════
// HITDASH — CrossDrawCorrelation v1.0.0
//
// The midday and evening draws of the same day are generated by
// the same physical machine on the same day. This creates a weak
// but real correlation between them (~5-8% above random for p1).
//
// If predicting EVENING: condition on TODAY's MIDDAY result.
// If predicting MIDDAY:  condition on YESTERDAY's EVENING result.
//
// Builds a transition matrix: midday_pair → evening_pair counts,
// then looks up the anchor pair to get conditional probabilities.
// For MIDDAY prediction, the reverse matrix is used.
//
// Fuente: hitdash.ingested_results
// ═══════════════════════════════════════════════════════════════

import type { Pool } from 'pg';
import pino from 'pino';
import type { GameType, DrawType } from '../../types/agent.types.js';
import type { AnalysisPeriod, PairHalf } from '../../types/analysis.types.js';

const logger = pino({ name: 'CrossDrawCorrelation' });

const LAPLACE_SMOOTHING = 0.001;
const FLAT_SCORE        = 0.01;

function extractPair(
  p1: number, p2: number, p3: number, p4: number, half: PairHalf
): string {
  if (half === 'ab') return `${p1}${p2}`;
  if (half === 'cd') return `${p3}${p4}`;
  return `${p2}${p3}`; // 'du'
}

function flatScores(): Record<string, number> {
  const scores: Record<string, number> = {};
  for (let x = 0; x <= 9; x++) {
    for (let y = 0; y <= 9; y++) {
      scores[`${x}${y}`] = FLAT_SCORE;
    }
  }
  return scores;
}

function yesterday(todayStr: string): string {
  const d = new Date(todayStr);
  d.setDate(d.getDate() - 1);
  return d.toISOString().split('T')[0]!;
}

export class CrossDrawCorrelation {
  constructor(private readonly pool: Pool) {}

  async runPairs(
    game_type: GameType,
    draw_type: DrawType,
    half: PairHalf,
    _period: AnalysisPeriod = 90
  ): Promise<Record<string, number>> {
    const start = Date.now();

    try {
      // ── STEP 1: Determine anchor draw ────────────────────────────────
      const today = new Date().toISOString().split('T')[0]!;
      const anchorDrawType: DrawType = draw_type === 'evening' ? 'midday' : 'evening';
      const anchorDrawDate: string   = draw_type === 'evening' ? today : yesterday(today);

      // ── STEP 2: Query anchor pair ─────────────────────────────────────
      const anchorRes = await this.pool.query<{
        p1: number; p2: number; p3: number; p4: number;
      }>(
        `SELECT p1, p2, p3, p4
         FROM hitdash.ingested_results
         WHERE game_type = $1
           AND draw_type = $2
           AND draw_date = $3
         LIMIT 1`,
        [game_type, anchorDrawType, anchorDrawDate]
      );

      if (anchorRes.rows.length === 0) {
        logger.info(
          { game_type, draw_type, half, anchor_draw_type: anchorDrawType, anchor_draw_date: anchorDrawDate },
          'CrossDrawCorrelation: anchor not found — returning flat scores'
        );
        return flatScores();
      }

      const ar = anchorRes.rows[0]!;
      const anchorPair = extractPair(ar.p1, ar.p2, ar.p3, ar.p4, half);

      logger.info(
        { game_type, draw_type, half, anchor_draw_type: anchorDrawType, anchor_draw_date: anchorDrawDate, anchor_pair: anchorPair },
        'CrossDrawCorrelation: anchor found'
      );

      // ── STEP 3: Build transition matrix from cross-draw history ───────
      // We always build: transMatrix[midday_pair][evening_pair] = count
      const histRes = await this.pool.query<{
        m_p1: number; m_p2: number; m_p3: number; m_p4: number;
        e_p1: number; e_p2: number; e_p3: number; e_p4: number;
      }>(
        `SELECT
           m.p1 AS m_p1, m.p2 AS m_p2, m.p3 AS m_p3, m.p4 AS m_p4,
           e.p1 AS e_p1, e.p2 AS e_p2, e.p3 AS e_p3, e.p4 AS e_p4
         FROM hitdash.ingested_results m
         JOIN hitdash.ingested_results e
           ON m.game_type = e.game_type
          AND m.draw_date = e.draw_date
         WHERE m.game_type = $1
           AND m.draw_type = 'midday'
           AND e.draw_type = 'evening'
           AND m.draw_date >= CURRENT_DATE - interval '365 days'`,
        [game_type]
      );

      const totalPairs = histRes.rows.length;

      logger.info(
        { game_type, draw_type, half, transition_pairs: totalPairs },
        'CrossDrawCorrelation: transition pairs loaded'
      );

      if (totalPairs === 0) {
        return flatScores();
      }

      // ── STEP 4: Build midday→evening transition matrix ────────────────
      const transMatrix = new Map<string, Map<string, number>>();

      for (const row of histRes.rows) {
        const midPair = extractPair(row.m_p1, row.m_p2, row.m_p3, row.m_p4, half);
        const evePair = extractPair(row.e_p1, row.e_p2, row.e_p3, row.e_p4, half);

        if (!transMatrix.has(midPair)) transMatrix.set(midPair, new Map());
        const matRow = transMatrix.get(midPair)!;
        matRow.set(evePair, (matRow.get(evePair) ?? 0) + 1);
      }

      // ── STEP 5 & 6: Look up anchor pair, handle direction ─────────────
      let lookupMatrix: Map<string, Map<string, number>>;

      if (draw_type === 'evening') {
        // Forward: midday_anchor → evening_prediction
        lookupMatrix = transMatrix;
      } else {
        // STEP 6 — Reverse: build evening→midday matrix
        const reverseMatrix = new Map<string, Map<string, number>>();
        for (const [midPair, eveMap] of transMatrix.entries()) {
          for (const [evePair, count] of eveMap.entries()) {
            if (!reverseMatrix.has(evePair)) reverseMatrix.set(evePair, new Map());
            const revRow = reverseMatrix.get(evePair)!;
            revRow.set(midPair, (revRow.get(midPair) ?? 0) + count);
          }
        }
        lookupMatrix = reverseMatrix;
      }

      const row = lookupMatrix.get(anchorPair);

      // ── STEP 7 & 8: Compute scores with Laplace smoothing ─────────────
      const scores: Record<string, number> = {};

      if (!row || row.size === 0) {
        // Anchor pair was never seen as a conditioner — flat + smoothing
        for (let x = 0; x <= 9; x++) {
          for (let y = 0; y <= 9; y++) {
            scores[`${x}${y}`] = FLAT_SCORE + LAPLACE_SMOOTHING;
          }
        }
      } else {
        const rowTotal = Array.from(row.values()).reduce((s, v) => s + v, 0);

        for (let x = 0; x <= 9; x++) {
          for (let y = 0; y <= 9; y++) {
            const p = `${x}${y}`;
            const count = row.get(p) ?? 0;
            // Conditional probability + Laplace smoothing
            scores[p] = (count / rowTotal) + LAPLACE_SMOOTHING;
          }
        }
      }

      // ── STEP 9: Return scores (AnalysisEngine normalizes them) ─────────
      logger.debug(
        { game_type, draw_type, half, anchor_pair: anchorPair, elapsed_ms: Date.now() - start },
        'CrossDrawCorrelation.runPairs done'
      );

      return scores;

    } catch (err) {
      logger.error(
        { game_type, draw_type, half, err },
        'CrossDrawCorrelation: DB error — returning flat scores'
      );
      return flatScores();
    }
  }
}
